config/routes.rb
Rails.application.routes.draw do
  get 'cashier/add'

  get 'cashier/remove'

  get 'cashier/update_quantity'

  get 'cashier/close_client'

  get 'cashier/index'

  resources :items
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cashier_controller.rb
class CashierController < ApplicationController

  def index
     @cashier = session[:cashier] || {}
  end

  def add
    name = params[:name]
    id = params[:id]
    cashier = session[:cashier] ||= {}
    cashier[id] = (cashier[id] || 0) + 1

    redirect_to :action => :index
  end

  def remove
  end

  def update_quantity
  end

  def close_client
  end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :price, :image_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cashier_helper.rb
module CashierHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/cashier/add.html.erb
<h1>Cashier#add</h1>
<p>Find me in app/views/cashier/add.html.erb</p>

app/views/cashier/close_client.html.erb
<h1>Cashier#close_client</h1>
<p>Find me in app/views/cashier/close_client.html.erb</p>

app/views/cashier/index.html.erb
<h1>Caixa</h1>

<% total = 0 %>

<table>
	<% @cashier.each do |id, quantity| %>
		<% item = Item.find(id) %>
		<tr>
			<td><%= image_tag item.image_name, :height => "30", :width => "30%" %></td>
			<td ><%= item.name %></td>
			<td width="60"><%= quantity %></td>
			<td width="60"><%= number_to_currency item.price, :unit => "R$ " %></td>
			<td width="60"><%= number_to_currency item.price*quantity, :unit => "R$ " %></td>
		

		</tr>
		<% total += quantity * item.price %>
	<% end %>

	<tr>
		<td colspan="4">Total: </td>
		<td><%= number_to_currency total, :unit => "R$"%></td>
	</tr>

</table>

app/views/cashier/remove.html.erb
<h1>Cashier#remove</h1>
<p>Find me in app/views/cashier/remove.html.erb</p>

app/views/cashier/update_quantity.html.erb
<h1>Cashier#update_quantity</h1>
<p>Find me in app/views/cashier/update_quantity.html.erb</p>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :item_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :item_description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :item_price %>
  </div>

  <div class="field">
    <%= form.label :image_name %>
    <%= form.text_field :image_name, id: :item_image_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editando Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Mostrar Item', @item %> |
<%= link_to 'Voltar', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Itens</h1>
<%= link_to 'Novo Item', new_item_path %>




<table>
  <thead>
    <tr>
     
    </tr>
  </thead>

  <style type="text/css">
    .name{
      font.size: 15pt;
      font-weight: bold;
      margin-bottom: 16px;
      margin-top: 10px;


    }

    .name a, a:hover{

       color:orange;
    }


    .description{
      margin-bottom: 10x;
    }

    .price{
      color:orange;
      font-weight: 800;
      font-size: 10pt;
      text-align: right;
    }

  </style>

  <div><%= link_to 'Caixa', :controller => :cashier, :action => :index %></div>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= image_tag item.image_name, :height => "60%", :width => "60%" %></td>
        <td>
          <div class= "name"><%= link_to item.name,item %></div>
          <div class= "description"><%= item.description %></div>
          
          
          <div class="links">
            <%= link_to 'Mostrar Item', item %>
            <%= link_to 'Editar', edit_item_path(item) %>
            <%= link_to 'Excluir', item, method: :delete, data: { confirm: 'Are you sure?' } %>    
          </div>
          <div class= "price"><%= number_to_currency item.price, :unit => "R$ " %></div>
          <%= link_to 'Adicionar ao Caixa', :controller => :cashier, :action => :add, :id => item %>
        </td>
      </tr>

      <tr><td colspan="2">
        <hr/>
      </td></tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/items/new.html.erb
<h1>Novo Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Voltar', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @item.image_name %>

<p>
  <strong>Nome:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Preço:</strong>
  <%='R$'%>
  <%= @item.price %>
</p>



<%= link_to 'Editar', edit_item_path(@item) %> |
<%= link_to 'Voltar', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CaixaCapital</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>